package com.hphant.constants
{
	public class AddressConstants
	{
		public function AddressConstants()
		{
		}
		public static const STATES:Array = [{name:'Alabama', abr:'AL'},
											{name:'Alaska', abr:'AK'},
											{name:'Arizona', abr:'AZ'},
											{name:'Arkansas', abr:'AR'},
											{name:'California', abr:'CA'},
											{name:'Colorado', abr:'CO'},
											{name:'Connecticut', abr:'CT'},
											{name:'Delaware', abr:'DE'},
											{name:'Florida', abr:'FL'},
											{name:'Georgia', abr:'GA'},
											{name:'Hawaii', abr:'HI'},
											{name:'Idaho', abr:'ID'},
											{name:'Illinois', abr:'IL'},
											{name:'Indiana', abr:'IN'},
											{name:'Iowa', abr:'IA'},
											{name:'Kansas', abr:'KS'},
											{name:'Kentucky', abr:'KY'},
											{name:'Louisiana', abr:'LA'},
											{name:'Maine', abr:'ME'},
											{name:'Maryland', abr:'MD'},
											{name:'Massachusetts', abr:'MA'},
											{name:'Michigan', abr:'MI'},
											{name:'Minnesota', abr:'MN'},
											{name:'Mississippi', abr:'MS'},
											{name:'Missouri', abr:'MO'},
											{name:'Montana', abr:'MT'},
											{name:'Nebraska', abr:'NE'},
											{name:'Nevada', abr:'NV'},
											{name:'New Hampshire', abr:'NH'},
											{name:'New Jersey', abr:'NJ'},
											{name:'New Mexico', abr:'NM'},
											{name:'New York', abr:'NY'},
											{name:'North Carolina', abr:'NC'},
											{name:'North Dakota', abr:'ND'},
											{name:'Ohio', abr:'OH'},
											{name:'Oklahoma', abr:'OK'},
											{name:'Oregon', abr:'OR'},
											{name:'Pennsylvania', abr:'PA'},
											{name:'Rhode Island', abr:'RI'},
											{name:'South Carolina', abr:'SC'},
											{name:'South Dakota', abr:'SD'},
											{name:'Tennessee', abr:'TN'},
											{name:'Texas', abr:'TX'},
											{name:'Utah', abr:'UT'},
											{name:'Vermont', abr:'VT'},
											{name:'Virginia', abr:'VA'},
											{name:'Washington', abr:'WA'},
											{name:'West Virginia', abr:'WV'},
											{name:'Wisconsin', abr:'WI'},
											{name:'Wyoming', abr:'WY'}];
	}
}