CREATE TABLE `bmcd`.`content_attributes` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`dt` DATETIME NOT NULL ,
`blnvalid` BOOL NOT NULL DEFAULT '1',
`src` VARCHAR( 100 ) NULL DEFAULT NULL ,
`href` VARCHAR( 100 ) NULL DEFAULT NULL ,
`width` INT NULL DEFAULT NULL ,
`height` INT NULL DEFAULT NULL ,
`selected` BOOL NULL DEFAULT NULL
) ENGINE = MYISAM ;