--DEPRACATED
CREATE TABLE `sessions` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`dt` DATETIME NOT NULL ,
`blnvalid` BOOL NOT NULL DEFAULT '1',
`key` VARCHAR (32) NOT NULL UNIQUE,
`ip` VARCHAR(15) NULL,
`user_id` INT NOT NULL DEFAULT '-1'
) ENGINE = MYISAM ;