-- DEPRACATED

CREATE TABLE `users` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`dt` DATETIME NOT NULL ,
`blnvalid` BOOL NOT NULL DEFAULT '1',
`email` VARCHAR (50) NOT NULL UNIQUE,
`password_hash` VARCHAR (32) NOT NULL DEFAULT '34a87ccd2a8d6e3d3a766ae1258b22e2',
`access_level` INT NOT NULL DEFAULT '1'
) ENGINE = MYISAM ;